on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  ping_glitch:
    name: Ping glitch
    runs-on: ubuntu-latest
    steps:
      - name: ping
        run: |
          echo 'hi'
