on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'

jobs:
  ping_glitch:
    name: Ping glitch
    runs-on: ubuntu-latest
    steps:
      - name: ping
        run: |
          curl https://protect-tests.glitch.me
